language: node_js
node_js:
  - 8
script:
  - npm run lint
  - npm run build
  # Ensure there are no file changes due to the build
  - test -z $(git diff-index --name-only HEAD -- lib)
  - npm run test
